### ISSUE TITLE
Add reference about disabling keyring for poetry

### ISSUE THREAD

**Issue by psschwei** [i-am-bee/bee-python-sdk#3]
Trying to install the dependencies for the examples using Poetry will get stuck trying to access the system keyring:

```
$ poetry install -vvv
Using virtualenv: /tmp/bee-python-sdk/venv
Installing dependencies from lock file

Finding the necessary packages for the current system

Package operations: 29 installs, 2 updates, 0 removals, 8 skipped

  - Installing h11 (0.14.0): Pending...
Checking if keyring is available
  - Installing sniffio (1.3.1): Pending...
  - Installing typing-extensions (4.12.2): Pending...
[keyring:keyring.backend] Loading KWallet
[keyring:keyring.backend] Loading SecretService
[keyring:keyring.backend] Loading Windows
[keyring:keyring.backend] Loading chainer
[keyring:keyring.backend] Loading libsecret
[keyring:keyring.backend] Loading macOS
Using keyring backend 'SecretService Keyring'

```

To disable the keyring when installing (which in any case seems like a good idea, as Poetry shouldn't need access to the keyring to install dependencies), one can use the null keyring by running 

```
POETRY_KEYRING_ENABLED=false poetry install
``` 

instead. To save users a web search on trying to figure out why poetry is hanging, we should add a brief note to the README with that option.

**Comment by jezekra1** [comment]
See comment: https://github.com/i-am-bee/bee-python-sdk/pull/4#issuecomment-2483549407

Most likely an extreme edge case, we don't want to unnecessary pollute the README.
Let's reopen this if more people encounter this issue.
